#! /bin/bash

#set -e
#pwd

IFS='.' read -r target extension _ <<<"$1"
[[ $target ]] || { echo "File name invalid." >&2; exit 1; }
if [[ $extension && $extension != "tex" ]] ; then
	echo "File extensions: $extension not supported." >&2
	exit 1
fi

build="build"

zero="|                    | (00%)      \r"
twentyfive="|#####               | (25%)      \r"
thirty="|#######             | (33%)      \r"
fifty="|##########          | (50%)      \r"
sixtysix="|#############       | (66%)      \r"
seventyfive="|###############     | (75%)      \r"
hundred="|####################| (100%)     \n"

if [ -e "$build" ] ; then
    rm -rf $build
    mkdir $build
else
    mkdir $build
fi

args="-shell-escape -interaction=nonstopmode -output-directory=$build"

if [ -e latex.log ] ; then
    rm "latex.log"
fi
touch "latex.log"

if [ $# == 2 ] ; then
    if [ $2 == "-q" ] ; then
	echo -ne "Compiling $zero"
	pdflatex $args "$target.tex" > "latex.log"
	echo -ne "Compiling $thirty"
	pdflatex $args "$target.tex" > "latex.log"
	echo -ne "Compiling $sixtysix"
	pdflatex $args "$target.tex" > "latex.log"
	echo -ne "Compiling $hundred"
    fi
else
    echo -ne "Compiling $zero"
    pdflatex $args "$target.tex" > "latex.log"
    echo -ne "Compiling $twentyfive"
    biber "$build/$target.bcf" > "latex.log"
    echo -ne "Compiling $fifty"
    pdflatex $args "$target.tex" > "latex.log"
    echo -ne "Compiling $seventyfive"
    pdflatex $args "$target.tex" > "latex.log"
    echo -ne "Compiling $hundred"
fi

if [ -e "$build/$target.pdf" ] ; then
	cp "$build/$target.pdf" .
else
	cat latex.log
fi

